import Head from 'next/head'
import type {NextPage} from 'next'
import WheelOfFortune from "../components/WheelOfFortune/WheelOfFortune";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Christmas calendar draw</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <WheelOfFortune/>
            </main>
        </div>
    )
}

export default Home
