name: build and deploy main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /christmas-calendar-draw
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install packages
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --immutable
      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - name: Export static files
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: export
      - name: Deploy🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: out